### ISSUE TITLE
prune statements seems not understood with version 0.42

### ISSUE THREAD

**Issue by chabotsi** [mgedmin/check-manifest#115]
Hi,

Since the last version 0.42, I have check-manifest failures on many projects while everything was working fine with version 0.41.

It seems related to the `prune` statements in the MANIFEST.in.

For instance, with check-manifest==0.42, I have the following error

```bash
$ tox -re check-manifest
check-manifest recreate: /home/schabot/src/public/nazca/.tox/check-manifest
check-manifest installdeps: check-manifest
check-manifest installed: check-manifest==0.42,importlib-metadata==1.6.0,pep517==0.8.2,pkg-resources==0.0.0,toml==0.10.0,zipp==3.1.0                                         
check-manifest run-test-pre: PYTHONHASHSEED='3430514152'
check-manifest runtests: commands[0] | /home/schabot/src/public/nazca/.tox/check-manifest/bin/python -m check_manifest
lists of files in version control and sdist do not match!
missing from sdist:
  .gitlab-ci.yml
  python-nazca.spec
suggested MANIFEST.in rules:
  include *.spec
  include *.yml
```

while I have the following statements in the MANIFEST.in

```
[…]
prune .gitlab-ci.yml
prune *.spec
```

With the previous version of check-manifest, and (of course) the same MANIFEST.in, it was working:

```bash
$ tox -e check-manifest
check-manifest create: /builds/open-source/nazca/.tox/check-manifest
check-manifest installdeps: check-manifest==0.41
check-manifest installed: check-manifest==0.41,pep517==0.8.2,toml==0.10.0
check-manifest run-test-pre: PYTHONHASHSEED='1543202351'
check-manifest run-test: commands[0] | /builds/open-source/nazca/.tox/check-manifest/bin/python -m check_manifest
lists of files in version control and sdist match
___________________________________ summary ____________________________________
  check-manifest: commands succeeded
  congratulations :)
```

Thank you for your help,

**Comment by 1313e** [comment]
Adding to this, it seems that a `recursive-exclude` into a `recursive-include` no longer works either (so, the situation where the former excludes something that the latter includes again).

For example, I have a single directory called `colormaps` in my package, from which only files should be included that start with `cm_`. All other files must be excluded.
I have always achieved this by recursively excluding everything in that folder, and then recursively including everything in the folder that starts with `cm_`, like this:
```
recursive-exclude cmasher colormaps/*
recursive-include cmasher colormaps/cm_*
```
Since v0.42, this no longer works.
Now, it seems like only the second statement is taken into account and the first is ignored, as I now get a report about all files (except the ones starting with `cm_`) not being included or excluded by the MANIFEST.in file.

**Comment by mgedmin** [comment]
The `prune` directive is meant for directories, not files.  check-manifest 0.42 now actually uses the same code imported from setuptools to convert MANIFEST.in exclude directives into regular expressions used for exclusion, so it should be more accurate (with one exception I'll mention later).

The difference you observe is the starting set of files: check-manifest assumes you want everything from the version control system, while setuptools by default picks only a subset of files (basically the source code and a README).  But if you happen to pip install a setuptools plugin like setuptools-git, then setuptools itself will start with a full list of files from the git repository, and it'll see your `prune` directives, and it'll ignore them just like check-manifest does today, because these are files, not directories

`exclude .gitlab-ci.yml *.spec` should work for you.

> Adding to this, it seems that a recursive-exclude into a recursive-include no longer works either (so, the situation where the former excludes something that the latter includes again).

This is the exception I was going to mention earlier: check-manifest currently processes exclude directives and ignores include directives.  I plan to fix it one of these days.

I'm surprised by the "no longer works" part, as check-manifest never processed include directives.

I'm guessing the change in behavior in 0.42 comes from the same source: now that I use setuptools' own code, `*` no longer matches `/` characters.  A recursive-exclude of `colormaps/*` excludes only files directly in the colormaps directory (in any directory named `colormaps` actually`, but doesn't do anything about subdirectories.  To match subdirectories, you need to use `colormaps/**`.  Or, to keep things simpler, you could do

```
recursive-exclude cmasher/colormaps *
recursive-include cmasher/colormaps cm_*
```

This is another of those situations where if you had setuptools-git installed, `python3 setup.py sdist` would start including those png/jscm files you intended to exclude, so I think check-manifest is correct to warn about them.

HTH!

**Comment by chabotsi** [comment]
Thank you for your detailed anwser. I update the manifests and I close this issue.
