### ISSUE TITLE
Make check-manifest available as a wheel (.whl)

### ISSUE THREAD

**Issue by mcarans** [mgedmin/check-manifest#44]
Please make package available as a wheel (.whl) 

whl is the new standard and this package isn't available as a .whl from Pypi (https://pypi.python.org/pypi/).

WinPython supports whl files in its Control Panel as of 3.4.2.4 and 2.7.9.2. Even http://www.lfd.uci.edu/~gohlke/pythonlibs/ which used to contain exe files now contains only whl files. So would be good for this package to be available in this format. Thanks.

**Comment by mgedmin** [comment]
See #43 and especially [this comment](https://github.com/mgedmin/check-manifest/pull/43#issuecomment-68607423) for reasons why that isn't done yet.

Wheels are very important for Python packages that ship C extension modules, but check-manifest isn't such a package.  For pure Python packages wheels don't really add much.  A few microseconds shaved off the time of `pip install`.  That's why it's not a high priority for me.

**Comment by mcarans** [comment]
Thanks for getting back. Python is a mess when it comes to packaging and wheels seem to be the way for that mess to be cleared up. The more projects that adopt it the sooner wheels become the standard. http://pythonwheels.com/ shows a fair number of packages are already available, so I hope that if you do get a spare moment one day, you will reconsider.

**Comment by mgedmin** [comment]
Oh, absolutely.  I just have no good way of doing that now, without breaking something for a subset of the users.

**Comment by mgedmin** [comment]
check-manifest 0.25 is available as a universal wheel from PyPI.
