### ISSUE TITLE
should probably ignore "empty" directories

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/check-manifest#55]
1. git clone https://github.com/zopefoundation/zope.configuration
2. check-manifest zope.configuration

Expected results:
```
lists of files in version control and sdist match
```

Actual results:
```
lists of files in version control and sdist do not match!
missing from sdist:
  docs/_static
```

What happens here is that `docs/_static/` has a `.gitignore` inside (which is what makes Git pick it up), but then we filter it out (since #54).

Extra info: zope.configuration was at commit 39ffa68f48bd6787545fb945844af2635a3da9e3 at the time bug was filed.

**Comment by mgedmin** [comment]
It's quite possible that I'm wrong and that check-manifest is correct: perhaps unzipping the sdist should create that empty directory.  Otherwise Sphinx might break.

**Comment by mauritsvanrees** [comment]
AFAIK really empty directories never end up in git and never and up in an sdist. But in some cases you do want a directory in there, so adding a hidden file makes sense, as long as that file itself is then included in the sdist via the manifest. So I think check-manifest is right in complaining.

Since the `.gitignore` file is empty and is not meant for ignoring files, I would rename it to `.keep` or `.gitkeep`. At least those are names that I sometimes see for cases like this. The file should have a short text explaining why it is there, for example: "This file exists to keep this directory in source control and in the distribution, as Sphinx needs it.".
