### ISSUE TITLE
check-manifest prints "ERROR:" lines on commented out lines

### ISSUE THREAD

**Issue by slashfoo** [mgedmin/check-manifest#66]
The following MANIFEST.in yields the lines on the bottom even if everything else is fine, this doesn't stop the run tho.

```
# ./ root folder
include *.rst
include *.txt
exclude conftest.py

# docs/ folder
include docs/Makefile
recursive-include docs *.rst
recursive-include docs *.py
recursive-include docs/_static *
recursive-include docs/_templates *
recursive-exclude docs/_build *

# everywhere
recursive-exclude * __pycache__
recursive-exclude * *.py[co]
```

```
ERROR: Trailing slashes are not allowed in MANIFEST.in on Windows: ./
ERROR: Trailing slashes are not allowed in MANIFEST.in on Windows: docs/
lists of files in version control and sdist match
```

**Comment by mgedmin** [comment]
Haha!  Amazing, thank you for this bug report, will fix.

**Comment by mgedmin** [comment]
Background: the warning was introduced for #37.

Reference: here's how distutils [parse MANIFEST.in files](https://github.com/python/cpython/blob/59335c5d2354320dada452bfbbbe93bac38e3581/Lib/distutils/command/sdist.py#L296):
- comments are stripped
- blank lines are ignored
- continuation lines are joined
- leading and trailing whitespace is stripped

The same distutils.text_file.TextFile() class is used since [at least Python 2.6](https://github.com/python/cpython/blob/2.6/Lib/distutils/command/sdist.py#L322), so I think maybe I should just use it in check-manifest.

**Comment by mgedmin** [comment]
0.31 is out with this fix.
